# Generated by Django 4.1 on 2022-08-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mytable',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('Course_Over_Ground', models.CharField(db_column='Course_Over_Ground', max_length=200)),
                ('Latitude', models.CharField(db_column='Latitude', max_length=200)),
                ('Longitude', models.CharField(db_column='Longitude', max_length=200)),
                ('Ship_ID', models.IntegerField(db_column='Ship_ID')),
                ('Speed', models.IntegerField(db_column='Speed')),
                ('Time', models.TimeField(db_column='Time')),
            ],
            options={
                'db_table': 'mytable',
            },
        ),
    ]
