# Generated by Django 4.1 on 2022-08-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytable',
            name='Course_Over_Ground',
            field=models.CharField(db_column='course_over_ground', max_length=200),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Latitude',
            field=models.CharField(db_column='latitude', max_length=200),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Longitude',
            field=models.CharField(db_column='longitude', max_length=200),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Ship_ID',
            field=models.IntegerField(db_column='ship_id'),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Speed',
            field=models.IntegerField(db_column='speed'),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Time',
            field=models.TimeField(db_column='time'),
        ),
    ]
